apiVersion: v1
kind: ConfigMap
data:
  application.properties: |+
    blobstore.gcs.balhut.bucket.name=${BUCKET_NAME}
    blobstore.gcs.kakka.bucket.name={{ .Values.gcs.kakka.bucketName }}
    blobstore.gcs.kakka.kartverket.addresses.folder=kartverket/addresses
    blobstore.gcs.haya.bucket.name={{ .Values.gcs.haya.bucketName }}
    blobstore.gcs.haya.latest.filename_without_extension=balhut_latest
    blobstore.gcs.haya.import.folder=import
    spring.profiles.active=gcs-blobstore
    spring.application.name=balhut
    spring.main.web-application-type=NONE
    bahamut.retry.maxAttempts=3
    bahamut.retry.maxDelay=5000
    bahamut.retry.backoff.multiplier=3
metadata:
  name: {{ template "balhut.name" . }}-config
  namespace: {{ template "balhut.name" . }}
  labels:
  {{- include "common.labels" . | indent 4 }}