apiVersion: v1
kind: ConfigMap
data:
  application.properties: |+
    blobstore.gcs.balhut.bucket.name={{ .Values.gcp.balhut.bucketName }}
    blobstore.gcs.kakka.bucket.name={{ .Values.gcp.kakka.bucketName }}
    blobstore.gcs.haya.bucket.name={{ .Values.gcp.haya.bucketName }}
    blobstore.gcs.latest.filename_without_extension=balhut_latest
    blobstore.gcs.kakka.kartverket.addresses.folder=kartverket/addresses
    blobstore.gcs.haya.import.folder=import
    spring.profiles.active=gcs-blobstore
    management.endpoints.enabled-by-default=false
    management.endpoint.health.enabled=true
    management.health.defaults.enabled=false
    management.endpoint.health.probes.enabled=true
    management.endpoint.health.group.readiness.include=readinessState
    management.endpoints.web.exposure.include=health
    management.endpoints.jmx.exposure.exclude=*
    spring.cloud.task.closecontextEnabled=true
    spring.application.name=balhut
    logging.level.org.springframework.cloud.task=DEBUG
metadata:
  name: {{ template "balhut.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "common.labels" . | indent 4 }}
