gcp_project = "entur-1287"
gcp_storage_project = "entur-ror-prod"
gcp_resources_project = "entur-ror-prod"
kube_namespace = "production"
bucket_balhut_instance_name = "balhut-production"
bucket_kakka_instance_name = "kakka-production"